### ISSUE TITLE
Medication Details

### ISSUE THREAD

**Issue by bowmanmc** [AppliedIS/AgileBPA#3]
As a user, I'd like to see the details of a saved medication from my medication list. This should have user entered details as well as information from the fda (adverse effects, ingredients, allergy info, etc...)

**Comment by jmmcnj** [comment]
Allow user to click on drug to see details, showing only the list at the My Medications page.  Details should include drug name, generic name, Adverse Events and drug interactions information from Label API

**Comment by jmmcnj** [comment]
Did not include drug interactions, would be completed in a later release
