### ISSUE TITLE
Add View Details Button

### ISSUE THREAD

**Issue by allisonchristman** [AppliedIS/AgileBPA#33]
Making a change, make the Medications a list with just the name of the medication and make that clickable. Remove grey background.

Eg.

Tylenol
Motrin
Metaformin

**Comment by allisonchristman** [comment]
Making a change, make the Medications a list with just the name of the medication and make that clickable. Remove grey background.

Eg.

Tylenol
Motrin
Metaformin

**Comment by jmmcnj** [comment]
Completed with "View Details" button, meets requirements
