### ISSUE TITLE
Apply Modal Confirmation post Signup/create profile

### ISSUE THREAD

**Issue by jmmcnj** [AppliedIS/AgileBPA#43]
Apply the Sweet Alert to the success/failure of the Signup/Create profile entry page.  Use the following text:

"Congratulations, You have successfully created a Profile.  <Button 'Start Adding Medications' (url to My Medications page)>"

**Comment by bowmanmc** [comment]
Fixed in builds >= 19. Also took off the auto-close option on the modal
